16 image endpoint
saskia002/kaardirakendus pull request #18
Opened 2023-11-15 20:13 UTC by saskia002

2023-11-16 07:03 UTC, klillenb requested changes
lisasin mõned kommentaarid

2023-11-16 07:03 UTC, klillenb commented on backend/src/main/java/tlu/kaardirakendus/akustika/service/AkustikaService.java
> +                    .body(null);
Response body võiks sisalda mingit error sõnumit ikkagist, et vajadusel oleks lihtsam diagnoosida (ei pea silmas seda et täpselt pritsiks ette kus mida valesti läks)
Samas 404 on väga üldine ja ei peagi antud juhul täpselt ütlema et mingit asja pole olemas.

2023-11-16 07:03 UTC, klillenb commented on backend/src/main/java/tlu/kaardirakendus/akustika/service/AkustikaService.java
> +                                .imagePath(
kas pilt oleks üldse antud pathilt kättesaadav? Kui server saab serveerida neid pilte lihtsalt Pathi pealt, siis ei peakski multipart response'ga jamama

2023-11-16 07:03 UTC, klillenb commented on backend/src/main/java/tlu/kaardirakendus/akustika/service/IAkustikaService.java
> +
üleliigne whitespace

2023-11-16 07:03 UTC, klillenb commented on stage/images/1/2.jpeg
see DBsse kirja ei lähe, niiet kas on mõtet laadida?

2023-11-21 07:14 UTC, saskia002 commented on backend/src/main/java/tlu/kaardirakendus/akustika/controller/AkustikaImageController.java
> +    @GetMapping(value = "/stage/{stageId}/image/{imageId}")
ei

2023-11-21 07:15 UTC, saskia002 commented on backend/src/main/java/tlu/kaardirakendus/akustika/controller/AkustikaImageController.java
> +    public ResponseEntity<byte[]> getStageImagesById(@PathVariable Integer id) {
saab, las jääb võimalus

2023-11-21 07:15 UTC, saskia002 commented on backend/src/main/java/tlu/kaardirakendus/akustika/dto/StageImageInfoDto.java
> +    private String imagePath;
palun vaata controlleri andmetüüpi

2023-11-21 07:15 UTC, saskia002 commented on backend/src/main/java/tlu/kaardirakendus/akustika/service/AkustikaService.java
> +                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(null);
ei, mujal pole kasutusel

2023-11-21 07:16 UTC, saskia002 commented on backend/src/main/java/tlu/kaardirakendus/akustika/service/AkustikaService.java
> +                    .body(null);
ei, mujal pole kasutusel

2023-11-21 07:16 UTC, saskia002 commented on backend/src/main/java/tlu/kaardirakendus/akustika/service/AkustikaService.java
> +                                .imagePath(
palun vaata contontrolleri andme tüüpi

2023-11-21 07:16 UTC, saskia002 commented on backend/src/main/java/tlu/kaardirakendus/akustika/service/IAkustikaService.java
> +
okei    !

2023-11-21 07:18 UTC, saskia002 commented on backend/src/main/java/tlu/kaardirakendus/akustika/service/IAkustikaService.java
> +
U+0009

2023-11-21 07:19 UTC, saskia002 commented
@klillenb palun vaata üle! :)

2023-11-28 08:57 UTC, klillenb requested changes

2023-11-28 08:57 UTC, klillenb commented on stage/images/1/2.jpeg
milleks see reposse laadida kui ta DBsse ka ei lähe?

2023-11-29 06:35 UTC, saskia002 commented on stage/images/1/2.jpeg
fixed

2023-11-30 06:45 UTC, klillenb approved these changes
lgtm

2023-11-30 06:45 UTC, merged