20 images into db
saskia002/kaardirakendus pull request #21
Opened 2023-12-01 14:41 UTC by saskia002

2023-12-04 10:34 UTC, klillenb requested changes
added comments

2023-12-04 10:34 UTC, klillenb commented on backend/src/main/java/tlu/kaardirakendus/akustika/service/AkustikaService.java
> +            }
atm tundub nagu closing } pole aligned joonele, kuna vaatan Mare maja arvutist ss idk kas githubi eripära v tõesti paigast ära, selletõttu ka try nihkes

2023-12-04 10:34 UTC, klillenb commented on backend/src/main/resources/db/migration/V1_13__insert_stage_image_data.sql
> +CALL insert_images('Käru laululava', 'Käru', 10);
Käru teist korda siin, esimene kord line 45

2023-12-04 10:34 UTC, klillenb commented on backend/src/main/resources/db/migration/V1_13__insert_stage_image_data.sql
> +        END LOOP;
shift+tab

2023-12-04 19:44 UTC, saskia002 commented on backend/src/main/resources/db/migration/V1_13__insert_stage_image_data.sql
> +call image_insert('Iisaku laululava', 'lisaku_2.jpg');
Ei viitsi

2023-12-05 17:46 UTC, klillenb approved these changes

2023-12-05 17:46 UTC, merged